name: MMTk OpenJDK 11 (with LXR)

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        debug-level: ["slowdebug"]
        variant: ["mmtk-lxr"]
    name: jdk11-mmtk-lxr-${{ matrix.debug-level }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MMTk/OpenJDK binding
        uses: actions/checkout@v3
        with:
          repository: mmtk/mmtk-openjdk
          path: ./mmtk-openjdk
      - name: Extract MMTk-OpenJDK revision
        id: extract-mmtk-openjdk-revision
        run: |
          cd ./mmtk-openjdk
          echo "::set-output name=mmtk-openjdk-revision::$(git rev-parse HEAD)"
      - name: Extract OpenJDK revision
        id: extract-openjdk-revision
        run: echo "::set-output name=openjdk-revision::$(sed -n 's/^openjdk_version.=."\(.*\)"$/\1/p' < mmtk-openjdk/mmtk/Cargo.toml)"
      - name: Checkout JDK MMTk fork
        uses: actions/checkout@v3
        with:
          repository: mmtk/openjdk
          path: ./openjdk
          ref: ${{ steps.extract-openjdk-revision.outputs.openjdk-revision }}
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install build dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y
          build-essential
          libfreetype6-dev
          libcups2-dev
          libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev
          libasound2-dev
          libffi-dev
          autoconf
          zip
          unzip
          libfontconfig1-dev
          pigz
      - name: Configure OpenJDK
        run: sh configure --disable-warnings-as-errors --with-debug-level=${{ matrix.debug-level }}
        working-directory: ./openjdk
      - name: Build OpenJDK
        run: make CONF=linux-x86_64-normal-server-${{ matrix.debug-level }} THIRD_PARTY_HEAP=$PWD/../mmtk-openjdk/openjdk product-bundles
        working-directory: ./openjdk
      - name: Upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jdk11-mmtk-lxr-${{ matrix.debug-level }}-bundles
          path: ./openjdk/build/linux-x86_64-normal-server-${{ matrix.debug-level }}/bundles/*
      - name: Find and generate bundle file
        id: find-file
        run: |
          current_date=$(date +'%Y%m%d')
          echo "date: $(date)" > ./versions.txt
          echo "variant: ${{ matrix.debug-level }}, ${{ matrix.variant }}" >> ./versions.txt
          echo "openjdk: ${{ steps.extract-openjdk-revision.outputs.openjdk-revision }}" >> ./versions.txt
          echo "mmtk-openjdk: ${{ steps.extract-mmtk-openjdk-revision.outputs.mmtk-openjdk-revision }}" >> ./versions.txt
          bundle_name=$(ls ./openjdk/build/linux-x86_64-normal-server-${{ matrix.debug-level }}/bundles/*.tar.gz | grep -v -e symbols -e demos)
          bundle_file=jdk11-linux-x86_64-normal-server-${{ matrix.debug-level }}-${{ matrix.variant }}-$current_date.tar.gz
          bundle_file_latest=jdk11-linux-x86_64-normal-server-${{ matrix.debug-level }}-${{ matrix.variant }}.tar.gz
          mv $bundle_name ./archive.tar.gz
          gunzip archive.tar.gz
          tar rf archive.tar ./versions.txt
          gzip archive.tar
          cp ./archive.tar.gz ./$bundle_file_latest
          mv ./archive.tar.gz ./$bundle_file
          echo "::set-output name=bundle-file::$bundle_file_latest"
          echo "::set-output name=bundle-file-latest::$bundle_file"
      - name: Upload bundle ${{ steps.find-file.outputs.bundle-file }}
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ steps.find-file.outputs.bundle-file }}
          release_id: 77066034
          overwrite: true
      - name: Upload bundle ${{ steps.find-file.outputs.bundle-file-latest }}
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ steps.find-file.outputs.bundle-file-latest }}
          release_id: 77066034
          overwrite: true
